### PR TITLE
check-and-lint Node 12 actions are deprecated (#2)

### PR DESCRIPTION
**Pull request by HGlab01**
fix for #2

### CODE REVIEW

**Comment by Apollon77** [comment]
thank you!

**Comment by HGlab01** [comment]
> thank you!

welcome! Issue #2 is (still) open and I guess you have to "tag" the version to get effective, isn't it?
Same for https://github.com/ioBroker/testing-action-adapter

**Comment by AlCalzone** [comment]
Yep, I'll take care of it later. The release action is also affected probably.

**Comment by AlCalzone** [comment]
@HGlab01 pro tip: If you had put "fixes: #2" in the PR description, merging would have closed the issue.

**Pull request merged**
